from src.db.connection import get_connection


def init_schema():
    conn = get_connection()
    conn.execute("""
        CREATE TABLE IF NOT EXISTS products (
            product_id BIGINT PRIMARY KEY,
            product_type VARCHAR,
            category VARCHAR,
            product_tags VARCHAR,
            images_array VARCHAR,
            vendor VARCHAR,
            inventory_quantity BIGINT,
            gross_amount_exc_tax_product DOUBLE,
            description VARCHAR
        )
    """)
    conn.execute("""
        CREATE TABLE IF NOT EXISTS enrichissements (
            id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            product_id BIGINT,
            enriched_description VARCHAR,
            material VARCHAR,
            care_instructions VARCHAR,
            style VARCHAR,
            seo_keywords VARCHAR,
            model_used VARCHAR,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (product_id) REFERENCES products(product_id)
        )
    """)
    conn.commit()
