mappings:
  "#N/A": "Autres"
  "A definir": "Autres"
  "A définir": "Autres"
  "ACC LLG": "Autres"
  "ACCESSOIRES": "Autres"
  "ACCESSORIES MEN": "Autres"
  "AQUAHERO": "Autres"
  "Accessoires": "Autres"
  "Accessoires - Enfant - Mixte": "Bébé & Enfant"
  "Accessoires Et Chaussures": "Chaussures"
  "Accessoires Iphones 12": "Autres"
  "Affiches": "Autres"
  "Air Jordan": "Autres"
  "Anaki": "Autres"
  "Anses": "Sacs & Maroquinerie"
  "Art De La Table": "Autres"
  "Arts De La Table": "Autres"
  "Assiettes": "Autres"
  "Assises": "Autres"
  "Autres": "Autres"
  "Bague": "Sacs & Maroquinerie"
  "Bagues": "Sacs & Maroquinerie"
  "Bain": "Maillots De Bain"
  "Ballerines": "Chaussures"
  "Band Of Outsiders": "Autres"
  "Bas": "Autres"
  "Bas lingerie": "Lingerie"
  "Baskets": "Chaussures"
  "Baskets Homme": "Chaussures"
  "Bateaux": "Chaussures"
  "Bavoirs": "Autres"
  "Beachwear": "Maillots De Bain"
  "Beauté Des Mains & Pieds": "Autres"
  "Belts": "Accessoires"
  "Bermudas": "Pantalons"
  "Bijoux": "Bijoux"
  "Bikini Bottoms": "Maillots De Bain"
  "Birkenstock": "Autres"
  "Blazers": "Hauts"
  "Bloomer/Culotte - Bébé - Fille": "Lingerie"
  "Blouses": "Hauts"
  "Blouses Et Chemises": "Hauts"
  "Bodies & Pyjamas": "Lingerie"
  "Bodies Et Combinaisons": "Autres"
  "Bodies Et Lingerie": "Lingerie"
  "Body Et Combinaisons": "Hauts"
  "Bonnets": "Accessoires"
  "Bonpoint": "Autres"
  "Bootcut Jeans": "Pantalons"
  "Boots": "Chaussures"
  "Bottes": "Chaussures"
  "Bottes Et Bottines": "Chaussures"
  "Bottes de randonnée": "Chaussures"
  "Bottines": "Autres"
  "Bottoms": "Autres"
  "Boucles D'Oreilles": "Bijoux"
  "Boucles D’Oreilles": "Bijoux"
  "Boucles d'Oreilles": "Bijoux"
  "Boucles d'oreilles": "Bijoux"
  "Boutchou": "Bébé & Enfant"
  "Boxers": "Lingerie"
  "Boîtes À Bijoux": "Bijoux"
  "Bracelet": "Bijoux"
  "Bracelets": "Bijoux"
  "Bracelets Et Joncs": "Bijoux"
  "Bras": "Autres"
  "Brassières": "Autres"
  "Briefs": "Autres"
  "Broches": "Bijoux"
  "Bébé": "Autres"
  "Bébé Garçon": "Autres"
  "CARDIGAN": "Vestes & Manteaux"
  "CHEMISE": "Hauts"
  "CIVIL": "Autres"
  "COUSSIN ET PLAID": "Autres"
  "Cables": "Autres"
  "Caleçons": "Autres"
  "Cardigans": "Vestes & Manteaux"
  "Casques": "Accessoires"
  "Casquettes": "Accessoires"
  "Ceintures": "Accessoires"
  "Chaises": "Autres"
  "Chanel": "Autres"
  "Chapeaux": "Accessoires"
  "Chaussettes": "Autres"
  "Chaussettes Et Collants": "Autres"
  "Chausson Espadrille": "Chaussures"
  "Chaussons Bébés": "Chaussures"
  "Chaussures": "Chaussures"
  "Chaussures - Bébé - Fille": "Chaussures"
  "Chaussures - Bébé - Mixte": "Chaussures"
  "Chaussures - Chaussures - Fille": "Chaussures"
  "Chaussures De Ville": "Chaussures"
  "Chaussures Et Accessoires": "Chaussures"
  "Chemise": "Hauts"
  "Chemises": "Hauts"
  "Chemises & Tops": "Hauts"
  "Chemises / Blouses": "Hauts"
  "Chemises Et T-Shirts": "Hauts"
  "Chemises Et Top": "Hauts"
  "Chemises Et Tops": "Hauts"
  "Coats": "Vestes & Manteaux"
  "Coffrets": "Autres"
  "Col Rond": "Autres"
  "Colliers": "Bijoux"
  "Combinaisons": "Autres"
  "Combinaisons & Robes": "Robes & Jupes"
  "Complément Alimentaire Peau": "Autres"
  "Corps": "Autres"
  "Corps - Bébé - Fille": "Bébé & Enfant"
  "Costumes & Smokings": "Autres"
  "Coupelles": "Autres"
  "Couverts": "Autres"
  "Cravates": "Accessoires"
  "Créoles": "Autres"
  "Culottes": "Lingerie"
  "Culottes Et Bas": "Lingerie"
  "Culottes Menstruelles": "Lingerie"
  "Cyclistes": "Pantalons"
  "CÉRÉMONIE": "Autres"
  "DENIM": "Pantalons"
  "DERBIES": "Chaussures"
  "Derbies": "Chaussures"
  "Doudounes": "Vestes & Manteaux"
  "Draps Plats": "Autres"
  "Dress": "Robes & Jupes"
  "Décoration": "Autres"
  "Element": "Autres"
  "Enfant Fille": "Bébé & Enfant"
  "Enfant Garçon": "Bébé & Enfant"
  "Ensembles": "Autres"
  "Ensembles Pour Bébés Et Tout-Petits": "Autres"
  "Escarpins": "Chaussures"
  "Espadrilles": "Chaussures"
  "Faux Ongles": "Autres"
  "Femme": "Autres"
  "Fille": "Bébé & Enfant"
  "Fonds De Robes": "Robes & Jupes"
  "Foulards": "Accessoires"
  "GILET": "Vestes & Manteaux"
  "Gilets": "Vestes & Manteaux"
  "Golden Goose": "Autres"
  "Gowns": "Robes & Jupes"
  "Gucci": "Autres"
  "Handbags": "Sacs & Maroquinerie"
  "Hartford": "Autres"
  "Hats": "Autres"
  "Hauts": "Hauts"
  "Hauts De Lingerie": "Hauts"
  "Hauts De Maillot": "Hauts"
  "Hauts De Maillots": "Hauts"
  "Hermès": "Autres"
  "Homme": "Autres"
  "Hoodies": "Pulls & Maille"
  "Housses Et Trousses": "Sacs & Maroquinerie"
  "Hugo Boss": "Autres"
  "Hygiène": "Autres"
  "IKKS": "Autres"
  "Isothermes": "Autres"
  "JAC": "Autres"
  "JACKET": "Vestes & Manteaux"
  "JACKETS": "Vestes & Manteaux"
  "JUMPER": "Pulls & Maille"
  "JUPE": "Robes & Jupes"
  "Jacket": "Vestes & Manteaux"
  "Jardin": "Autres"
  "Jeans": "Pantalons"
  "Jeans & Pantalons": "Pantalons"
  "Jeans Et Pantalons": "Pantalons"
  "Jimmy Choo": "Autres"
  "Joggers": "Autres"
  "Joggings": "Pantalons"
  "Jupe": "Robes & Jupes"
  "Jupe mi-longue": "Robes & Jupes"
  "Jupes": "Robes & Jupes"
  "Jupes Et Robes": "Robes & Jupes"
  "Jupes Et Shorts": "Pantalons"
  "Jupes et Shorts": "Pantalons"
  "KEYRING & CHARM": "Autres"
  "Kimonos": "Hauts"
  "Knitwear": "Pulls & Maille"
  "LINGERIE": "Lingerie"
  "LUMINAIRE": "Autres"
  "Lampes À Poser": "Autres"
  "Leggings": "Pantalons"
  "Linge De Bain": "Maillots De Bain"
  "Linge De Lit": "Autres"
  "Linge De Maison": "Autres"
  "Lingerie": "Lingerie"
  "Lingerie Bas": "Lingerie"
  "Long Sleeved Top": "Hauts"
  "Luminaires": "Autres"
  "Lunettes": "Accessoires"
  "Lunettes De Vue": "Accessoires"
  "MAROQUINERIE": "Sacs & Maroquinerie"
  "MEN": "Autres"
  "Maille": "Pulls & Maille"
  "Maille Et Sweats": "Pulls & Maille"
  "Mailles Et Sweats": "Pulls & Maille"
  "Maillot": "Maillots De Bain"
  "Maillots": "Maillots De Bain"
  "Maillots 1 Pièce": "Maillots De Bain"
  "Maillots 1 piÃ¨ce": "Maillots De Bain"
  "Maillots De Bain": "Maillots De Bain"
  "Maillots De Bain 1 Pièce": "Maillots De Bain"
  "Maillots De Bain Femme": "Maillots De Bain"
  "Maillots de bain": "Maillots De Bain"
  "Maison": "Autres"
  "Manchette": "Bijoux"
  "Manteau": "Vestes & Manteaux"
  "Manteaux": "Vestes & Manteaux"
  "Manteaux Et Vestes": "Vestes & Manteaux"
  "Manteaux/Veste - Bébé - Mixte": "Vestes & Manteaux"
  "Maroquinerie": "Sacs & Maroquinerie"
  "Masques": "Accessoires"
  "Men, KNITWEAR, LMTS0194": "Pulls & Maille"
  "Midi Skirts": "Robes & Jupes"
  "Midi dresses": "Robes & Jupes"
  "Mini": "Autres"
  "Mini Skirts": "Robes & Jupes"
  "Mitaines": "Accessoires"
  "Mocassins": "Chaussures"
  "Mono boucle": "Bijoux"
  "Mules": "Chaussures"
  "Mules Et Sandales": "Chaussures"
  "Nightwear": "Lingerie"
  "Nouveau Né": "Autres"
  "Nouveautés salon": "Autres"
  "Nuit": "Lingerie"
  "Néon LED à forme": "Autres"
  "OVERSHIRT": "Hauts"
  "PAP": "Autres"
  "PS by PAUL SMITH": "Autres"
  "PULL": "Pulls & Maille"
  "Paniers": "Autres"
  "Pantalon": "Pantalons"
  "Pantalons": "Pantalons"
  "Pantalons & Leggings": "Pantalons"
  "Pantalons & Shorts": "Pantalons"
  "Pantalons Et Combinaisons": "Pantalons"
  "Pantalons Et Jeans": "Pantalons"
  "Pantalons Et Joggings": "Pantalons"
  "Pantalons Et Jupes": "Pantalons"
  "Pantalons Et Shorts": "Pantalons"
  "Pants": "Pantalons"
  "Parapluies": "Accessoires"
  "Parkas": "Vestes & Manteaux"
  "Parure De Couette": "Autres"
  "Peignoirs": "Lingerie"
  "Peinture Par Numéros": "Autres"
  "Pendentifs": "Bijoux"
  "Petit Bateau": "Chaussures"
  "Petit Mobilier": "Autres"
  "Petite Maroquinerie": "Sacs & Maroquinerie"
  "Plaids": "Autres"
  "Plantes D'Intérieur": "Autres"
  "Plats": "Autres"
  "Pochettes": "Sacs & Maroquinerie"
  "Pochettes Et Sachets Ramasse-Crottes": "Sacs & Maroquinerie"
  "Pochettes Et Trousses": "Sacs & Maroquinerie"
  "Polos": "Hauts"
  "Ponchos": "Autres"
  "Porte-Chéquiers": "Autres"
  "Porte-Passeports": "Autres"
  "Portefeuilles": "Sacs & Maroquinerie"
  "Poubelle tri sélectif": "Autres"
  "Poufs": "Autres"
  "Prada": "Autres"
  "Prix": "Autres"
  "Produits Corps": "Autres"
  "Protections Solaires": "Autres"
  "Prêt-À-Porter": "Autres"
  "Prêt-à-porter": "Autres"
  "Pull": "Pulls & Maille"
  "Pullovers": "Pulls & Maille"
  "Pulls": "Pulls & Maille"
  "Pulls & Cardigans": "Vestes & Manteaux"
  "Pulls & Gilets": "Vestes & Manteaux"
  "Pulls & Sweats": "Pulls & Maille"
  "Pulls Col Rond": "Pulls & Maille"
  "Pulls Col Roulé": "Pulls & Maille"
  "Pulls Col V": "Pulls & Maille"
  "Pulls Cols Ronds": "Pulls & Maille"
  "Pulls Et Gilets": "Vestes & Manteaux"
  "Pulls Et Sweats": "Pulls & Maille"
  "Pumps": "Chaussures"
  "Pyjamas": "Lingerie"
  "ROBE": "Robes & Jupes"
  "RTW CLOTHING": "Autres"
  "Reiko": "Autres"
  "Removable straps": "Autres"
  "Robe mi-longue": "Robes & Jupes"
  "Robes": "Robes & Jupes"
  "Robes & Jupes": "Robes & Jupes"
  "Robes - Enfant - Fille": "Robes & Jupes"
  "Robes Et Combinaisons": "Robes & Jupes"
  "Robes Et Jupes": "Robes & Jupes"
  "Running": "Chaussures"
  "SANDALES PLATES": "Chaussures"
  "SHIRT": "Hauts"
  "SHOES": "Chaussures"
  "SIEGE SUR MESURE": "Autres"
  "SNEAKERS SIMONE": "Chaussures"
  "SURFWEAR GIRLS": "Autres"
  "SURFWEAR MEN": "Autres"
  "SWEATSHIRT": "Hauts"
  "SWIMWEAR": "Maillots De Bain"
  "Sabots": "Chaussures"
  "Sac hobo Femme": "Sacs & Maroquinerie"
  "Sac à Bandoulière": "Sacs & Maroquinerie"
  "Sac à Dos": "Sacs & Maroquinerie"
  "Sacs": "Sacs & Maroquinerie"
  "Sacs & Accessoires": "Sacs & Maroquinerie"
  "Sacs A Main": "Sacs & Maroquinerie"
  "Sacs Bandoulière": "Sacs & Maroquinerie"
  "Sacs Et Accessoires": "Sacs & Maroquinerie"
  "Sacs Et Bandoulières": "Sacs & Maroquinerie"
  "Sacs Et Maroquinerie": "Sacs & Maroquinerie"
  "Sacs Et Pochettes": "Sacs & Maroquinerie"
  "Sacs Pepa": "Sacs & Maroquinerie"
  "Sacs À Bandoulière": "Sacs & Maroquinerie"
  "Sacs À Main": "Sacs & Maroquinerie"
  "Sandales": "Chaussures"
  "Sandals": "Chaussures"
  "Serviettes": "Autres"
  "Sessùn": "Autres"
  "Sets De Valises": "Sacs & Maroquinerie"
  "Shirts": "Hauts"
  "Short Sleeved Top": "Pantalons"
  "Short dresses": "Pantalons"
  "Shorts": "Pantalons"
  "Shorts & Bermuda Shorts": "Pantalons"
  "Shoulder bags": "Sacs & Maroquinerie"
  "Silhouette": "Autres"
  "Skirts and shorts": "Pantalons"
  "Sleeveless Top": "Hauts"
  "Slides": "Chaussures"
  "Sneakers": "Chaussures"
  "Softshells": "Vestes & Manteaux"
  "Soin | Visage": "Autres"
  "Soutiens-Gorge Ampliformes": "Lingerie"
  "Strings": "Lingerie"
  "Suit jackets": "Vestes & Manteaux"
  "Sweat-shirt": "Hauts"
  "Sweaters": "Pulls & Maille"
  "Sweats": "Pulls & Maille"
  "Sweatshirt": "Hauts"
  "Sweatshirts": "Hauts"
  "T Shirt": "Hauts"
  "T-Shirt": "Hauts"
  "T-Shirts": "Hauts"
  "T-Shirts & Tops": "Hauts"
  "T-Shirts Et Chemises": "Hauts"
  "T-Shirts Et Tops": "Hauts"
  "T-shirt": "Hauts"
  "T-shirts": "Hauts"
  "T-shirts & Polos": "Hauts"
  "TALONS HAUT": "Hauts"
  "TEE SHIRT": "Hauts"
  "TOP": "Hauts"
  "TSHIRTS & TOPS": "Hauts"
  "Tables": "Autres"
  "Taies D'Oreiller": "Autres"
  "Talons Moyens": "Chaussures"
  "Tangas": "Lingerie"
  "Tapis": "Autres"
  "Tartine & Chocolat": "Autres"
  "Teddies": "Autres"
  "Tees": "Hauts"
  "Teint": "Autres"
  "Tongs": "Chaussures"
  "Top": "Hauts"
  "Tops": "Hauts"
  "Tops & Chemises": "Hauts"
  "Tops et T-Shirts": "Hauts"
  "Tote Bags": "Sacs & Maroquinerie"
  "Trouser": "Pantalons"
  "Trousses": "Sacs & Maroquinerie"
  "Tshirts": "Hauts"
  "Tuniques": "Hauts"
  "Turtleneck Sweaters": "Pulls & Maille"
  "Valises Long Séjour": "Sacs & Maroquinerie"
  "Vans": "Autres"
  "Vases": "Autres"
  "Veste": "Vestes & Manteaux"
  "Vestes": "Vestes & Manteaux"
  "Vestes & Manteaux, Homme": "Vestes & Manteaux"
  "Vestes Et Manteaux": "Vestes & Manteaux"
  "Vitamines et compléments alimentaires": "Autres"
  "Vêtements": "Autres"
  "WOMEN ACCESSORIES": "Autres"
  "WOVEN": "Autres"
  "Women, DRESSES, 7028I77-2135": "Robes & Jupes"
  "Women, KNITWEAR, WA296C12519A": "Pulls & Maille"
  "Women, TOP, 030-2WBET": "Hauts"
  "Women, TOP, T0001FQ23": "Hauts"
  "Wrap cardigans": "Vestes & Manteaux"
  "Zapatilla": "Autres"
  "Zyne": "Autres"
  "tote": "Sacs & Maroquinerie"
  "wallet": "Sacs & Maroquinerie"
  "Écharpes": "Autres"
default: "Autres"
